#!/usr/bin/env ruby

require 'rateless_bot'
require 'optparse'

options = {}

OptionParser.new do |opts|
  opts.banner = "Usage: rateless_bot [options]"

  opts.on("--nick NICK", "Bot's nick (required)") do |nick|
    options[:nick] = nick
  end

  opts.on("--server SERVER", "IRC server (required)") do |server|
    options[:server] = server
  end

  opts.on("--channel CHANNEL", "IRC channel (required)") do |channel|
    options[:channel] = '#' + channel
  end

  opts.on("--lastfm-api-key KEY", "LastFM API key") do |key|
    options[:lastfm_api_key] = key
  end

  opts.on("--lastfm-api-secret SECRET", "LastFM secret API key") do |secret|
    options[:lastfm_api_secret] = secret
  end

  opts.on("-h", "--help", "Prints this help") do
    puts opts
    exit
  end
end.parse!
puts options

bot = Cinch::Bot.new do
  configure do |c|
    c.nick = options[:nick]
    c.server = options[:server]
    c.channels << options[:channel]

    c.plugins.plugins = [CoinFlipper,
                         DiceRoller,
                         Help,
                         LastFM,
                         MagicEightBall,
                         VideoTitle]

    c.plugins.options = {
      LastFM => {
        :api_key => options[:lastfm_api_key],
        :api_secret => options[:lastfm_api_secret]
      }
    }
  end
end

bot.start
